// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePinPong.Data;

#nullable disable

namespace ePinPong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260809083949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ePinPong.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ePinPong.Models.Liga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojRegularnihTurnira")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sezona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Lige");
                });

            modelBuilder.Entity("ePinPong.Models.Mec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Igrac1ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igrac1PartnerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igrac2ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igrac2PartnerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoserNextMatchCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoserNextMatchSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivGrupe")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Odigran")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlacingRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoeniIgrac1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoeniIgrac2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipMeca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnirID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VrijemeMeca")
                        .HasColumnType("TEXT");

                    b.Property<string>("WinnerNextMatchCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerNextMatchSlot")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Igrac1ID");

                    b.HasIndex("Igrac1PartnerID");

                    b.HasIndex("Igrac2ID");

                    b.HasIndex("Igrac2PartnerID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("ePinPong.Models.Notifikacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Procitana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Notifikacije");
                });

            modelBuilder.Entity("ePinPong.Models.Pracenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PraceniID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PratilacID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PraceniID");

                    b.HasIndex("PratilacID");

                    b.ToTable("Pracenja");
                });

            modelBuilder.Entity("ePinPong.Models.Registracija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnikID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Odobren")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sesir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnirID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Registracije");
                });

            modelBuilder.Entity("ePinPong.Models.Turnir", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumKraja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrugoplasiraniID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kolo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LigaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIgraca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PobjednikID")
                        .HasColumnType("TEXT");

                    b.Property<int>("SistemTurnira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlikaUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipTakmicenja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrecaplasiraniID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LigaID");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Turniri");
                });

            modelBuilder.Entity("ePinPong.Models.TurnirPar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Igrac1ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Igrac2ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnirID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Igrac1ID");

                    b.HasIndex("Igrac2ID");

                    b.HasIndex("TurnirID");

                    b.ToTable("TurnirParovi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePinPong.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ePinPong.Models.Liga", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Organizator")
                        .WithMany()
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("ePinPong.Models.Mec", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac1")
                        .WithMany()
                        .HasForeignKey("Igrac1ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac1Partner")
                        .WithMany()
                        .HasForeignKey("Igrac1PartnerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac2")
                        .WithMany()
                        .HasForeignKey("Igrac2ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac2Partner")
                        .WithMany()
                        .HasForeignKey("Igrac2PartnerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ePinPong.Models.Turnir", "Turnir")
                        .WithMany("Mecevi")
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrac1");

                    b.Navigation("Igrac1Partner");

                    b.Navigation("Igrac2");

                    b.Navigation("Igrac2Partner");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("ePinPong.Models.Notifikacija", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("ePinPong.Models.Pracenje", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Praceni")
                        .WithMany()
                        .HasForeignKey("PraceniID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePinPong.Models.ApplicationUser", "Pratilac")
                        .WithMany()
                        .HasForeignKey("PratilacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Praceni");

                    b.Navigation("Pratilac");
                });

            modelBuilder.Entity("ePinPong.Models.Registracija", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Korisnik")
                        .WithMany("MojeRegistracije")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePinPong.Models.Turnir", "Turnir")
                        .WithMany("Registracije")
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("ePinPong.Models.Turnir", b =>
                {
                    b.HasOne("ePinPong.Models.Liga", "Liga")
                        .WithMany("Turniri")
                        .HasForeignKey("LigaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ePinPong.Models.ApplicationUser", "Organizator")
                        .WithMany("MojiTurniri")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("ePinPong.Models.TurnirPar", b =>
                {
                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac1")
                        .WithMany()
                        .HasForeignKey("Igrac1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePinPong.Models.ApplicationUser", "Igrac2")
                        .WithMany()
                        .HasForeignKey("Igrac2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePinPong.Models.Turnir", "Turnir")
                        .WithMany("TurnirParovi")
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igrac1");

                    b.Navigation("Igrac2");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("ePinPong.Models.ApplicationUser", b =>
                {
                    b.Navigation("MojeRegistracije");

                    b.Navigation("MojiTurniri");
                });

            modelBuilder.Entity("ePinPong.Models.Liga", b =>
                {
                    b.Navigation("Turniri");
                });

            modelBuilder.Entity("ePinPong.Models.Turnir", b =>
                {
                    b.Navigation("Mecevi");

                    b.Navigation("Registracije");

                    b.Navigation("TurnirParovi");
                });
#pragma warning restore 612, 618
        }
    }
}
